apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-k8s-web-deployment
  labels:
    app: weather-k8s-web-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: weather-k8s-web-deployment
  template:
    metadata:
      labels:
        app: weather-k8s-web-deployment
    spec:
      containers:
      - name: weather-k8s-web
        image: registry.digitalocean.com/weather-k8s/weather-k8s-web:v1
        envFrom:
          - secretRef:
              name: weather-k8s-web-prod-env
        env:
          - name: PORT
            value: "8001"
        ports:
        - containerPort: 8001
      imagePullSecrets:
        - name: weather-k8s   


---
apiVersion: v1
kind: Service
metadata:
  name: weather-k8s-web-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8001
  selector:
    app: weather-k8s-web-deployment
